<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Add.aspx.cs" Inherits="WebApplication1.Add" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
   


   
    <div class="container-fluid">
    <div class="row">
       
        <div class="col-md-3">
            <br />
            <table class="table">
                <tbody>
                   
                    <tr>
                        <th scope="row" style="height: 39px">marka</th>
                        <td style="height: 39px"><asp:TextBox ID="marka" runat="server"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <th scope="row">model</th>
                        <td><asp:TextBox ID="model" runat="server"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <th scope="row">rodzaj</th>
                        <td><asp:TextBox ID="rodzaj" runat="server"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <th>
                            <asp:Button ID="Button1" runat="server" Text="Dodaj" OnClick="Button1_Click" />
                        </th>
                    </tr>
                </tbody>
            </table>

            

           
        </div>
        
        
        
     </div>
    <div class="row">
        <div class="col-md-12">

            <br />

            <asp:Label ID="Label4" runat="server" Text="Zegarki"></asp:Label>
            <br />
            <asp:GridView ID="GridView1" runat="server" CssClass="table table-hover table-striped" GridLines="None" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting">
            </asp:GridView>

        </div>
        
    </div>
        </div>
   


   

</asp:Content>


